import Head from "next/head"
import React from "react"

import Layout from "../../components/Layout"

import NewListPost from "../../sections/Post/NewListPost"

export default function Explorar() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout withNav withFooter>
        <NewListPost />
      </Layout>
    </div>
  )
}
