import { Box, Text } from "@chakra-ui/react"
import Head from "next/head"
import React, { useContext } from "react"

import Layout from "../../components/Layout"

import NewListPost from "../../sections/Post/NewListPost"
import { DataContext } from "../../store/GlobalState"
// import NoPublication from "../../components/NoPublication"

export default function Explorar() {
  const { state } = useContext(DataContext)
  const { auth } = state
  if (!auth?.access_token) {
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Layout withNav withFooter>
          <Box
            d="flex"
            alignItems="center"
            justifyContent="center"
            w="full"
            h="3xl"
          >
            {/* TODO: Agregar imagen */}
            {/* <NoPublication /> */}
            <Text>Necesita iniciar sesion</Text>
          </Box>
        </Layout>
      </div>
    )
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout withNav withFooter>
        <NewListPost />
      </Layout>
    </div>
  )
}
