import Head from "next/head"
import Layout from "../../../components/Layout"
import Title from "../../../sections/Contact/Title"
import PhotosDescription from "../../../sections/Contact/PhotosDescription"
import Comentaries from "../../../sections/Contact/Comentaries"
import Creator from "../../../sections/Contact/Creator"
import Assessment from "../../../sections/Contact/Assessment"
import { useRouter } from "next/router"

export default function Home() {
  const router = useRouter()
  const { categoryid, categoryitemid } = router.query
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout withNav withFooter>
        <Title title={`Marketing para redes ${categoryitemid}`} />
        <PhotosDescription category={categoryid} />
        <Creator />
        <Assessment />
        <Comentaries />
      </Layout>
    </div>
  )
}
