import Head from "next/head"

import Layout from "../../components/Layout"

import CategoryTittle from "../../sections/Explore/CategoryTittle"

import RecomendedService from "../../sections/Explore/RecomendedService"

import OurServices from "../../sections/Explore/OurServices"

import InterestedService from "../../sections/Explore/InterestedService"

export default function Explorar({ categories, explore }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>

        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout withNav withFooter>
        <CategoryTittle categories={categories} />

        <RecomendedService recommended={explore.recommendedPosts} />
        <OurServices ourServices={explore.latestPosts} />
        <InterestedService interesting={explore.interestingPosts} />
      </Layout>
    </div>
  )
}

export const getServerSideProps = async context => {
  const resCategories = await fetch(
    `${process.env.API_BASE_URL}/api/category/categories`
  )
  const resExplore = await fetch(
    `${process.env.API_BASE_URL}/api/post/explore-posts`
  )
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore
  const dataCategories = await resCategories.json()
  const dataExplore = await resExplore.json()
  return {
    props: { categories: dataCategories, explore: dataExplore }
  }
}
