import Head from "next/head"

import Layout from "../../components/Layout"

import CategoryTittle from "../../sections/Explore/CategoryTittle"

import RecomendedService from "../../sections/Explore/RecomendedService"

import OurServices from "../../sections/Explore/OurServices"

import InterestedService from "../../sections/Explore/InterestedService"

export default function Explorar({ categories }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>

        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout withNav withFooter>
        <CategoryTittle categories={categories} />
        <RecomendedService />
        <OurServices />
        <InterestedService />
      </Layout>
    </div>
  )
}

export const getServerSideProps = async context => {
  // const id = context.params.id
  const res = await fetch(`${process.env.API_BASE_URL}/api/category/categories`)
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore
  const data = await res.json()
  return {
    props: { categories: data }
  }
}
