import Head from "next/head"
import SwiperCore, { Autoplay, Navigation } from "swiper/core"
import Layout from "../components/Layout"
import Title from "../sections/Contact/Title"
import PhotosDescription from "../sections/Contact/PhotosDescription"
import Comentaries from "../sections/Contact/Comentaries"
import Creator from "../sections/Contact/Creator"
import Assessment from "../sections/Contact/Assessment"
SwiperCore.use([Autoplay, Navigation])

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout withNav withFooter>
        <Title />
        <PhotosDescription />
        <Creator />
        <Assessment />
        <Comentaries />
      </Layout>
    </div>
  )
}
