import Head from "next/head"
import Navbar from "../components/Navbar"
import Footer from "../components/Footer"
import SwiperCore, { Autoplay, Navigation } from "swiper/core"
import Hero from "../sections/Home/Hero"
import React from "react"
import OurCategories from "../sections/Home/OurCategories"
import Reason from "../sections/Home/Reason"
import JoinUs from "../sections/Home/JoinUs"
import FeaturedServices from "../sections/Home/FeaturedServices"

SwiperCore.use([Autoplay, Navigation])

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <FeaturedServices />
      <Reason />
      <OurCategories />
      <JoinUs />
      <Footer />
    </div>
  )
}
