import Head from "next/head"
import { useContext } from "react"
import { Box, Text } from "@chakra-ui/react"
import Layout from "../components/Layout"

import Chat from "../sections/ShowChat/Chat"
import { DataContext } from "../store/GlobalState"

export default function Message() {
  const { state } = useContext(DataContext)
  const { auth } = state
  if (!auth?.access_token) {
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Layout withNav withFooter>
          <Box
            d="flex"
            alignItems="center"
            justifyContent="center"
            w="full"
            h="3xl"
          >
            {/* TODO: Agregar imagen */}
            <Text>Necesita iniciar sesion</Text>
          </Box>
        </Layout>
      </div>
    )
  }
  return (
    <div>
      <Layout withNav withFooter>
        <Chat />
      </Layout>
    </div>
  )
}
